name: Azure ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  azure-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - run: pip install -r requirements.txt

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: pip install azureml-core

      - run: python src/train.py